import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    LoginView: {
        flex: 1,
        backgroundColor: 'darkorchid',
        alignItems: 'center',
        justifyContent: 'flex-start',
    },
    BookingView: {
        backgroundColor: 'darkorchid',
        width: '100%',
        height: '100%',
    },
    BookingHeader: {
        backgroundColor: 'darkmagenta',
        height: '15%',
        width: '100%',
        marginTop: '10%',
    },
    BookingInfoSection: {
        flex: 1,
        height: '70%',
        width: '100%',
        backgroundColor: 'darkorchid',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center'
    },
    LogoutButtonSection: {
        alignItems: 'center',
        justifyContent: 'center',
        height: '100%',
        width: '50%',
    },
    LogoutButtonBackground: {
        backgroundColor: 'white',
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        height: '50%',
        width: '80%',
    },
    BookingUserInfo: {
        alignItems: 'center',
        justifyContent: 'center',
        width: '50%',
        fontSize: 20,
        color: 'white',
        textAlign: 'center'
    },
    BookingDatepickerSection: {
        height: '30%',
        width: '100%',
        backgroundColor: 'darkorchid',
        justifyContent: 'center',
        alignItems: 'center',
    },
    LoginForm: {
        flexDirection: 'column',
        justifyContent: 'space-around',
        width: '60%',
        height: '40%',
    },
    LoginTextInput: {
        backgroundColor: 'white',
        fontSize: 15,
        height: '15%',
        borderRadius: 10,
    },
    LoginTitleText: {
        color: 'white',
        fontSize: 30,
        padding: 20,
        marginTop: 50,
    },
    LoginNormalText: {
        fontSize: 20,
        color: 'white',
        height: '10%',
    },
    LoginButtonBackground: {
        backgroundColor: 'white',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        height: '15%'
    },
    LoginButtonText: {
        color: 'purple',
        fontSize: 20,
    },
    text: {
        fontSize: 40,
    },
    BookingContentSection: {
        height: '70%',
        width: '100%',
        marginTop: '5%',
    },
    BookingContentContainer: {
        flex: 1,
        flexDirection: 'row',
    },
    BookingContentContainerDeeper: {
        flex: 1,
        flexDirection: 'row',
    },
    BookingContent: {
        flexGrow: 1,
        width: '100%',
        backgroundColor: 'darkmagenta',
        borderColor: 'darkmagenta',
        alignItems: 'center',
        borderRadius: 20,
        padding: 10,
        paddingTop: 20,
        paddingBottomE: 20,
        borderWidth: 10,
        borderColor: 'darkorchid',
        rowGap: '15%',
        columnGap: '15%',
    },
    ParkingSpaceFree: { 
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'space-around',
        paddingTop: '5%',
        paddingBottom: '5%',
        height: 150, 
        maxHeight: 150,
        width: '80%', 
        borderWidth: 5,
        backgroundColor: 'green',   
        alignItems: 'center',
    },
    ParkingSpaceBusy: {
        flex: 1,
        flexDirection: 'column',
        justifyContent: 'space-around',
        paddingTop: '5%',
        paddingBottom: '5%',
        height: 150, 
        maxHeight: 150,
        width: '80%',  
        backgroundColor: 'red', 
        borderWidth: 5,
        alignItems: 'center',
    },
    SpaceNumber: {
        fontSize: 30,
        color: 'black',
    },
    BookingButton: {
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        height: '30%', 
        width: '80%',
        borderRadius: 10,
        borderWidth: 4,
        borderColor: 'black',
    },
    ReleaseButton: {
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 10,
        borderWidth: 4,
        backgroundColor: 'white',
        height: '30%', 
        width: '80%',
    },
    BookingButtonText: {
        fontSize: 20,
        color: 'black',
    },
    ReleaseButtonText: {
        fontSize: 20,
        color: 'black',
    },
    Name: {
        fontSize: 20,
        color: 'black',
    },
    Surname: {
        fontSize: 20,
        color: 'black',
    },
  });
  